### ISSUE TITLE
Does this plugin still work?

### ISSUE THREAD

**Issue by Silphatos** [burnhamup/galaxy-integration-indiegala#15]
Hello, it seems to connect IG account but doesn't import any games from showcase library at the moment.

**Comment by Danyelalejandro** [comment]
It happens exactly to me, and it keeps constantly desconecting all time
[plugin-indiegala-a1a85742-f3e0-42ae-bde9-64ab7d0321cf.log.zip](https://github.com/burnhamup/galaxy-integration-indiegala/files/5649039/plugin-indiegala-a1a85742-f3e0-42ae-bde9-64ab7d0321cf.log.zip)

**Comment by Danyelalejandro** [comment]
i have disabled ip check for bots and still happens

**Comment by PriorityDefault** [comment]
The plugin will import the library upon the initial connection, but will never update to add additional games, even though it shows it's connected. Even manually syncing integrations doesn't make it update. It has to be disconnected and reconnected to fetch new games. I'm guessing it's because of a change on IG's end.

**Comment by HappyRogue658** [comment]
The initial sync works. I don't know if it syncs games that are added later.

**Comment by burnhamup** [comment]
The new release https://github.com/burnhamup/galaxy-integration-indiegala/releases/tag/0.1.0 uses a different method for login/data retrieval which should address this issues.
