### ISSUE TITLE
What are the further plans for this plugin

### ISSUE THREAD

**Issue by Ohrwerk** [burnhamup/galaxy-integration-indiegala#17]
The plugin seems to work, but not all games from my showcase are displayed.
It is also not possible to install or at least download the games via this plugin.
I don't have a static IP address and when I log into Indiegala (WebBrowser) and access the showcase i always have to enter a verification code that i receive by email. That could at least explain why not all games are displayed.
However, I really wonder what is the point of this plugin if it is not possible to install or download a game from Indiegala.

**Comment by burnhamup** [comment]
When the platform doesn't have a client, you're really limited as to what you can do. In that sense, a plugin like this is more similar to something like a PlayStation plugin - it can tell you about the games, but you can't run them. 

That said, IndieGala recently released a barebones client. It's still not going to be possible to install and run games from GOG, since there isn't a way to talk to the client yet, but I might be able to hook up some more details.
